datasets:
  instruct_blip_coco2017_vig_test:
    data_type: images
    build_info:
      # annotation: /mnt/petrelfs/hanxiao/working/all_coco_images.json
      # image_ids: /mnt/petrelfs/hanxiao/working/coco_filter_ids.json
      # images: /mnt/petrelfs/share_data/zhaozhiyuan/InstructBLIP/COCO2017/

      annotation: /mnt/petrelfs/share_data/wangbin/mllm/vigc/data/coco/coco2017_extra36k.json
      # annotation: /mnt/petrelfs/share_data/wangbin/mllm/vigc/data/coco/vigc_bad_case.json  # hallucination samples
      image_ids: /mnt/petrelfs/hanxiao/working/coco_filter_ids.json
      images: /mnt/petrelfs/share_data/wangbin/mllm/data/coco2017
